name: build
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@1.1.0
    - uses: hadolint/hadolint-action@v2.1.0
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/vorteq/github-actions-runner/github-actions-runner
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch

    - name: Publish to Github Packages Registry
      env:
        githubTokenSecret: ${{ secrets.githubTokenSecret }}
        USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
        DOCKER_REGISTRY: ghcr.io/vorteq/github-actions-runner/github-actions-runner
      run: |
        docker login https://ghcr.io -u "$USERNAME_GITHUB" --password "$githubTokenSecret" 
        docker build . -t "$DOCKER_REGISTRY":focal-latest --network host
        docker push "$DOCKER_REGISTRY":focal-latest
